#Build settings
theme: minima
title: NATTDEV Servicios Digitales
author:
  name: nattdev
description: 

show_excerpts: true

minima:
  social_links:
    github: nattdev

defaults:
 -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: ":title"
